# Generated by Django 4.2.5 on 2023-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='client_image/')),
                ('short_des', models.TextField(default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clinets',
            },
        ),
    ]
