# Generated by Django 4.1.2 on 2023-10-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_remove_order_products_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main_app.product'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
